# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and deploy api and ui containers to Azure Web Apps

env:
  AZURE_WEBAPP_NAME_API: testApiP7  
  AZURE_WEBAPP_NAME_UI: testUiP7

on:
  push:
    branches:
      - master

permissions:
  contents: 'read'
  packages: 'write'





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image BACKEND to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}-api
          context: ./Patin_Clement_1_modele_012024/backend

      - name: Build and push container image FRONTEND to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}-ui
          context: ./Patin_Clement_1_modele_012024/frontend

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy API to Azure Web App
        id: deploy-api-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_API }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}-api'

      - name: Deploy UI to Azure Web App
        id: deploy-ui-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_UI }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_UI }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}-ui'